---
title: "gd"
author: "Jingmin Chen"
date: "2024-04-03"
output:
  word_document: default
  html_document: default
---
```{r}
```
```{r}
library(guardianapi)
# Please use the canonical form https://CRAN.R-project.org/package=guardianapi to link to this page.
```

#Data on feminist reporting five years after the start of the select metoo movement
```{r}
after_movement <- gu_content(query = "feminism", from_date = "2017-10-01", to_date = "2022-12-31")
```
#Data on feminist reporting in the five years prior to the start of the select metoo movement
```{r}
ctt_before_movement <- gu_content(query = "feminism", from_date = "2012-01-01", to_date = "2017-09-30")
```
```{r}
library(dplyr)
selected_ctt_after_movement <- select(ctt_after_movement, web_title, web_publication_date, body_text)
selected_ctt_before_movement <- select(ctt_before_movement, web_title, web_publication_date, body_text)

```
#Storage of data in two groups
```{r}
write.csv(selected_ctt_after_movement, "oselected_ctt_after_movement.csv", row.names = FALSE)
write.csv(selected_ctt_before_movement, "oselected_ctt_before_movement.csv", row.names = FALSE)
```

#Combining two sets of data, that is, for the decade 2012 to 2022
```{r}
# Read a previously saved CSV file
selected_ctt_after_movement <- read.csv("oselected_ctt_after_movement.csv", stringsAsFactors = FALSE)
selected_ctt_before_movement <- read.csv("oselected_ctt_before_movement.csv", stringsAsFactors = FALSE)

combined_data <- bind_rows(selected_ctt_before_movement, selected_ctt_after_movement)

write.csv(combined_data, "combined_data.csv", row.names = FALSE)
```

```{r}
library(lubridate)

combined_data <- combined_data %>%
  mutate(year = year(ymd_hms(web_publication_date)))


head(combined_data)

```
```{r}
write.csv(combined_data, "ocombined_data.csv", row.names = FALSE)
```


```{r}
data <- read.csv("ocombined_data.csv")
```


```{r}
# Get a simplified dataset containing only event content and year
selecteddata <- data %>%
  select(web_title, body_text, year)

head(selecteddata)
```
```{r}
library(dplyr)
library(tidytext)
library(stringr)

# Then convert the headlines to lower case and split the words while keeping the year columns

tidy_text <- selecteddata %>%
  mutate(web_title = tolower(web_title)) %>%
  unnest_tokens(word, web_title) %>%
  select(word, year) %>% 
  filter(str_detect(word, "^[a-z]+$"))


# Remove stop words
data(stop_words)
tidy_text <- tidy_text %>%
  anti_join(stop_words, by = "word")

# Remove specific HTML characters and other non-informative symbols
remove_reg <- c("&amp;", "&lt;", "&gt;", "<p>", "</p>", "&rsquo;", "&lsquo;", "&#39;",
                "<strong>", "</strong>", "rsquo", "em", "ndash", "nbsp", "lsquo", "strong")
tidy_text <- tidy_text %>%
  filter(!word %in% remove_reg)


# Print or view word frequency data

word_counts <- tidy_text %>%
  group_by(year) %>%
  count(word, sort = TRUE)
print(word_counts)
```

```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(scales)


# Create a new column to identify if it is an equality related word
titleword_counts <- word_counts %>%
  mutate(equalword = as.integer(grepl("equality|equity|fairness|rights|parity|justice|discrimination|liberty|empowerment|gap|diversity", word)))

# calculate the total number of gender-related words by year and the total number of words per year
ff_counts <- titleword_counts %>%
  group_by(year) %>%
  mutate(year_total = sum(n)) %>%
  filter(equalword == 1) %>%
  summarise(sum_equal = sum(n),
            year_total = min(year_total))

# Mapping changes in the proportion of gender-related terms in the total number of terms per year
ggplot(ff_counts, aes(x = year, y = sum_equal / year_total, group = 1)) +
  geom_line() +
  xlab("Year") +
  ylab("% Equality-Related Words") +
  scale_y_continuous(labels = percent_format(), expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica")

# display the graphs
ggplot(ff_counts, aes(x = year, y = sum_equal / year_total, group = 1)) +
  geom_line() +
  xlab("Year") +
  ylab("% Equality-Related Words") +
  scale_y_continuous(labels = percent_format(), expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica")

```
```{r}
# signal the year of the #MeToo movement in 2017.10
ggplot(ff_counts, aes(year, sum_equal / year_total, group=1)) +
  geom_line() +
  geom_vline(xintercept = 2017+ (10/12), col="red") +
  geom_text(aes(x=2017+ (11/12), label="#metoo movement", y=.0015), 
            colour="black", angle=90, text=element_text(size=8)) +
  xlab("Year") +
  ylab("% Equality-related words") +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica")
```
#sentiment analysis 
```{r}
library(quanteda)
library(tidytext)
library(dplyr)
library(lubridate)

# Load the required library
library(quanteda)
library(tidytext)
library(dplyr)
library(lubridate)

tidy_text_corpus <- corpus(tidy_text, text_field = "word", docvars = c("word", "year"))

# Checking the structure of corpus objects
print(tidy_text_corpus)
summary(tidy_text_corpus)

# tagging corpus text with tokens function and removing punctuation marks
toks_news <- tokens(tidy_text_corpus, remove_punct = TRUE)

# Checking tagged objects
print(toks_news)

# select only the "negative" and "positive" categories
data_dictionary_LSD2015_pos_neg <- data_dictionary_LSD2015[1:2]

toks_news_lsd <- tokens_lookup(toks_news, dictionary = data_dictionary_LSD2015_pos_neg)

# create a document document-feature matrix and group it by date
dfmat_news_lsd <- dfm(toks_news_lsd) %>% 
  dfm_group(groups = year)

# plot positive and negative valence over time
matplot(dfmat_news_lsd$year, dfmat_news_lsd, type = "l", lty = 1, col = 1:2,
        ylab = "Frequency", xlab = "")
grid()
legend("topleft", col = 1:2, legend = colnames(dfmat_news_lsd), lty = 1, bg = "white")
# plot overall sentiment (positive  - negative) over time

plot(dfmat_news_lsd$year, dfmat_news_lsd[,"positive"] - dfmat_news_lsd[,"negative"], 
     type = "l", ylab = "Sentiment", xlab = "")
grid()
abline(h = 0, lty = 2)
```







